// H-eL-seven - a schema-aware HL7 v2 to JSON translator
// Copyright (C) 2026 CavebatSoftware LLC - Grant DeFayette
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, version 3.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

//! Definition-driven HL7 v2 message generator, for bulk-testing the engine.
//!
//! Messages are generated by walking the same definition snapshots the engine
//! interprets: segment order comes from the trigger-event structure, field
//! presence from usage codes, coded values from the actual HL7 tables, and
//! composite values from the data-type component trees. A seeded RNG makes
//! every run reproducible.
//!
//! `messy` mode injects one or two known defects per message (dropped required
//! segment, blanked required field, corrupt NM/date, illegal repetition,
//! bogus table value, fields beyond the definition) and reports which, so a
//! bulk test can assert the validator catches them.

mod data;
mod persona;

use hl7_engine::defs::{DataTypeDef, Definitions, FieldDef, StructureItem};
use persona::Persona;

/// xorshift64 - deterministic, dependency-free.
pub struct Rng(u64);

impl Rng {
    pub fn new(seed: u64) -> Self {
        Rng(seed.max(1))
    }
    fn next(&mut self) -> u64 {
        let mut x = self.0;
        x ^= x << 13;
        x ^= x >> 7;
        x ^= x << 17;
        self.0 = x;
        x
    }
    fn range(&mut self, max: u64) -> u64 {
        self.next() % max.max(1)
    }
    fn chance(&mut self, p: f64) -> bool {
        (self.next() as f64 / u64::MAX as f64) < p
    }
    fn pick<'a, T>(&mut self, items: &'a [T]) -> &'a T {
        &items[(self.next() % items.len() as u64) as usize]
    }
}

pub struct Config {
    /// Probability an optional (O/RE) field is populated.
    pub optional_field_p: f64,
    /// Probability an optional segment/group is included.
    pub optional_seg_p: f64,
    /// Probability a message gets a Z-segment.
    pub z_segment_p: f64,
    /// Probability a message gets defects injected (with a report).
    pub messy: f64,
}

impl Default for Config {
    fn default() -> Self {
        Config {
            optional_field_p: 0.4,
            optional_seg_p: 0.35,
            z_segment_p: 0.1,
            messy: 0.0,
        }
    }
}

pub struct Generated {
    pub text: String,
    pub event: String,
    /// Human-readable descriptions of injected defects (empty = clean).
    pub defects: Vec<String>,
}

pub struct Generator<'d> {
    defs: &'d Definitions,
    rng: Rng,
    cfg: Config,
    control_seq: u64,
    /// msg_struct_id of the event currently being generated (for MSH-9.3).
    struct_id: String,
    /// Coherent patient/visit/facility world, re-rolled per message.
    p: Persona,
}

/// An OBX analyte chosen up front so OBX-2/3/5/6/7/8 all agree.
enum Analyte {
    /// (code, name, units, low, high, integer)
    Num(&'static (&'static str, &'static str, &'static str, f64, f64, bool)),
    /// (code, name, text value)
    Text(&'static (&'static str, &'static str, &'static str)),
}

impl<'d> Generator<'d> {
    pub fn new(defs: &'d Definitions, seed: u64, cfg: Config) -> Self {
        let mut rng = Rng::new(seed);
        let p = Persona::roll(&mut rng);
        Generator {
            defs,
            rng,
            cfg,
            control_seq: 0,
            struct_id: String::new(),
            p,
        }
    }

    /// Trigger events that exist in the loaded definitions, from a preferred
    /// list of common real-world message types.
    pub fn default_events(defs: &Definitions) -> Vec<String> {
        [
            "ADT_A01", "ADT_A03", "ADT_A08", "ORU_R01", "ORM_O01", "SIU_S12", "MDM_T02", "ACK",
        ]
        .iter()
        .filter(|e| defs.events.contains_key(**e))
        .map(|e| e.to_string())
        .collect()
    }

    /// Generate one message for the given trigger event. Returns None if the
    /// event is not in the definitions.
    pub fn generate(&mut self, event_key: &str) -> Option<Generated> {
        let event = self.defs.events.get(event_key)?;
        self.control_seq += 1;
        self.struct_id = self.resolve_struct_id(event_key);
        self.p = Persona::roll(&mut self.rng);

        // (line, segment_id, required) - the flags feed defect injection.
        let mut lines: Vec<(String, String, bool)> = Vec::new();
        let structure = event.structure.clone();
        self.walk(&structure, event_key, true, &mut lines);

        if self.rng.chance(self.cfg.z_segment_p) && lines.len() > 1 {
            let at = 1 + self.rng.range(lines.len() as u64 - 1) as usize;
            let z = format!(
                "ZED|{}|{}",
                self.rng.range(99),
                self.rng.pick(data::GENERIC)
            );
            lines.insert(at, (z, "ZED".into(), false));
        }

        // Segments required at the TOP level of the structure are the only
        // ones whose removal is guaranteed to be a detectable defect -
        // required segments inside optional/repeating groups can be legally
        // absent when their group doesn't materialize.
        let top_required: Vec<String> = event
            .structure
            .iter()
            .filter_map(|item| match item {
                StructureItem::Segment { segment, usage, .. }
                    if usage == "R" && segment != "MSH" =>
                {
                    Some(segment.clone())
                }
                _ => None,
            })
            .collect();

        let mut defects = Vec::new();
        if self.rng.chance(self.cfg.messy) {
            for _ in 0..=self.rng.range(2) {
                if let Some(d) = self.inject_defect(&mut lines, &top_required) {
                    defects.push(d);
                }
            }
        }

        let text: String = lines
            .iter()
            .map(|(l, _, _)| l.as_str())
            .collect::<Vec<_>>()
            .join("\r");
        Some(Generated {
            text: text + "\r",
            event: event_key.to_string(),
            defects,
        })
    }

    /// Walk structure items, generating segments. `force_first` pins the
    /// first eligible segment of a group instance: without it, a group whose
    /// lead segment is optional (OBSERVATION = {OBX O, NTE O*}) can emit only
    /// trailing segments like NTE, which a greedy parser must attach to an
    /// earlier slot, making the message ambiguous or structurally invalid.
    fn walk(
        &mut self,
        items: &[StructureItem],
        event_key: &str,
        force_first: bool,
        out: &mut Vec<(String, String, bool)>,
    ) {
        let mut force = force_first;
        for item in items {
            match item {
                StructureItem::Segment {
                    segment,
                    usage,
                    rpt,
                } => {
                    if usage == "B" || usage == "W" || usage == "X" {
                        continue;
                    }
                    let required = usage == "R";
                    if !required && !force && !self.rng.chance(self.cfg.optional_seg_p) {
                        continue;
                    }
                    let n = if rpt != "1" && self.rng.chance(0.35) {
                        2 + self.rng.range(2)
                    } else {
                        1
                    };
                    for i in 0..n {
                        let line = if segment == "MSH" {
                            self.gen_msh(event_key)
                        } else {
                            self.gen_segment(segment, i + 1)
                        };
                        out.push((line, segment.clone(), required));
                    }
                    force = false;
                }
                StructureItem::Group {
                    usage,
                    rpt,
                    children,
                    ..
                } => {
                    let required = usage == "R";
                    // Optional groups may dice out even under force: the
                    // binder skips them the same way, so the anchor duty
                    // simply carries to the next sibling.
                    if !required && !self.rng.chance(self.cfg.optional_seg_p) {
                        continue;
                    }
                    let n = if rpt != "1" && self.rng.chance(0.4) {
                        2 + self.rng.range(2)
                    } else {
                        1
                    };
                    for _ in 0..n {
                        self.walk(children, event_key, true, out);
                    }
                    force = false;
                }
            }
        }
    }

    /// The true message structure for MSH-9.3. HL7 table 0354 records the real sharing
    /// ("ADT_A01" covers "A01, A04, A08, A13") - prefer that when present.
    fn resolve_struct_id(&self, event_key: &str) -> String {
        let default = self
            .defs
            .events
            .get(event_key)
            .map(|e| e.msg_struct_id.clone())
            .unwrap_or_else(|| event_key.to_string());
        let Some(table) = self.defs.tables.get("0354") else {
            return default;
        };
        if table.values.contains_key(event_key) {
            return event_key.to_string();
        }
        let Some((ty, trigger)) = event_key.split_once('_') else {
            return default;
        };
        for (key, triggers) in &table.values {
            if key.starts_with(ty) && triggers.split(',').any(|t| t.trim() == trigger) {
                return key.clone();
            }
        }
        default
    }

    fn gen_msh(&mut self, event_key: &str) -> String {
        let (ty, trigger) = event_key.split_once('_').unwrap_or((event_key, ""));
        let msg_type = if trigger.is_empty() {
            ty.to_string()
        } else {
            // MSH-9.3 carries the message STRUCTURE, which several trigger
            // events can share (ADT_A08 -> ADT_A01).
            format!("{ty}^{trigger}^{}", self.struct_id)
        };
        format!(
            "MSH|^~\\&|{}|{}|{}|{}|{}||{}|GEN{:06}|P|{}",
            self.p.sending_app,
            self.p.facility_code,
            self.p.receiving_app,
            self.p.facility_code,
            self.p.now_dtm(),
            msg_type,
            self.control_seq,
            self.defs.version,
        )
    }

    fn gen_segment(&mut self, id: &str, set_id: u64) -> String {
        let Some(def) = self.defs.segments.get(id) else {
            return format!("{id}|1");
        };
        let mut fields: Vec<String> = Vec::new();

        // Pick the analyte up front so OBX-2/3/5/6/7/8 all agree.
        let analyte = (id == "OBX").then(|| {
            if self.rng.chance(0.8) {
                Analyte::Num(self.rng.pick(data::OBSERVATIONS))
            } else {
                Analyte::Text(self.rng.pick(data::TEXT_OBSERVATIONS))
            }
        });
        // A numeric result: mostly in range, sometimes plausibly out.
        let obx_value = analyte.as_ref().map(|a| match a {
            Analyte::Num((_, _, _, low, high, int)) => {
                let span = high - low;
                let frac = self.rng.range(1000) as f64 / 1000.0;
                let v = if self.rng.chance(0.85) {
                    low + span * frac
                } else if self.rng.chance(0.5) {
                    high + span * 0.25 * frac
                } else {
                    (low - span * 0.25 * frac).max(0.0)
                };
                if *int {
                    format!("{}", v.round() as i64)
                } else {
                    format!("{v:.1}")
                }
            }
            Analyte::Text((_, _, text)) => encode(text),
        });

        for (i, fdef) in def.fields.iter().enumerate() {
            let pos = i + 1;
            let value = if let (Some(analyte), true) =
                (&analyte, matches!(pos, 2 | 3 | 5 | 6 | 7 | 8 | 11))
            {
                match pos {
                    2 => {
                        let want = match analyte {
                            Analyte::Num(_) => "NM",
                            Analyte::Text(_) => "ST",
                        };
                        self.coded(want, fdef)
                    }
                    3 => {
                        let (code, name) = match analyte {
                            Analyte::Num((c, n, ..)) => (*c, *n),
                            Analyte::Text((c, n, _)) => (*c, *n),
                        };
                        self.ce(&fdef.data_type, code, name, "LN")
                    }
                    5 => obx_value.clone().unwrap(),
                    6 => match analyte {
                        Analyte::Num((_, _, unit, ..)) => {
                            self.ce(&fdef.data_type, unit, "", "UCUM")
                        }
                        Analyte::Text(_) => String::new(),
                    },
                    7 => match analyte {
                        Analyte::Num((_, _, _, low, high, int)) => {
                            if *int {
                                format!("{}-{}", *low as i64, *high as i64)
                            } else {
                                format!("{low:.1}-{high:.1}")
                            }
                        }
                        Analyte::Text(_) => String::new(),
                    },
                    8 => match analyte {
                        Analyte::Num((_, _, _, low, high, _)) => {
                            let v: f64 = obx_value.as_deref().unwrap().parse().unwrap_or(*low);
                            let flag = if v < *low {
                                "L"
                            } else if v > *high {
                                "H"
                            } else {
                                "N"
                            };
                            self.coded(flag, fdef)
                        }
                        Analyte::Text(_) => String::new(),
                    },
                    11 => self.coded("F", fdef), // result status: final
                    _ => unreachable!(),
                }
            } else if fdef.usage == "R" || self.rng.chance(self.cfg.optional_field_p) {
                if matches!(fdef.usage.as_str(), "B" | "W" | "X") {
                    String::new()
                } else {
                    let reps = if fdef.rpt != "1" && self.rng.chance(0.25) {
                        2
                    } else {
                        1
                    };
                    let mut values: Vec<String> = (0..reps)
                        .map(|_| self.value(&fdef.data_type, fdef, 0, Some(set_id), pos))
                        .collect();
                    // Persona-backed values are stable, so a "repetition" can
                    // come out identical - a duplicate says nothing, drop it.
                    values.dedup();
                    values.join("~")
                }
            } else {
                String::new()
            };
            fields.push(value);
        }
        while fields.last().is_some_and(|f| f.is_empty()) {
            fields.pop();
        }
        format!("{id}|{}", fields.join("|"))
    }

    /// A value for a data type: known composite types get a coherent typed
    /// build from the persona/catalogs; other composites -> components joined
    /// by ^ (depth 0) or & (depth 1); anything at depth 2, or primitive, -> leaf.
    fn value(
        &mut self,
        dt_id: &str,
        fdef: &FieldDef,
        depth: u8,
        set_id: Option<u64>,
        field_pos: usize,
    ) -> String {
        let _ = field_pos;
        if depth < 2 {
            if let Some(parts) = self.typed_parts(dt_id, fdef) {
                return self.join_parts(parts, dt_id, depth);
            }
        }
        match self.defs.data_types.get(dt_id) {
            Some(dt) if !dt.components.is_empty() && depth < 2 => {
                let sep = if depth == 0 { '^' } else { '&' };
                let comps = self.components(dt, depth, set_id);
                comps.join(&sep.to_string())
            }
            _ => self.leaf(dt_id, fdef, set_id),
        }
    }

    /// Coherent component lists for the common composite types. Returns None
    /// when the type has no dedicated build (-> generic recursion).
    fn typed_parts(&mut self, dt_id: &str, fdef: &FieldDef) -> Option<Vec<String>> {
        let name = fdef.name.as_str();
        // TS/DTM are composites in the defs (time + precision), so the field
        // name would be lost before the leaf's Birth/Admit rules - resolve
        // date coherence here, at field level.
        if matches!(dt_id, "TS" | "DTM") {
            let dtm = self.coherent_dtm(name);
            return Some(vec![dtm]);
        }
        let p = &self.p;
        Some(match dt_id {
            "XPN" | "PN" => {
                let person = if name.contains("Mother")
                    || name.contains("Next of Kin")
                    || name.contains("Contact")
                    || name.contains("Associated Part")
                    || name.contains("Guarantor")
                {
                    &p.kin
                } else {
                    &p.patient
                };
                vec![
                    encode(&person.family),
                    encode(&person.given),
                    person.middle.clone(),
                ]
            }
            "XCN" | "CN" => {
                let doc = &p.doctors[if name.contains("Referring") { 1 } else { 0 }];
                vec![doc.id.clone(), encode(&doc.family), encode(&doc.given)]
            }
            "XAD" | "AD" => vec![
                encode(&p.street),
                String::new(),
                p.city.to_string(),
                p.state.to_string(),
                p.zip.to_string(),
            ],
            "XTN" => vec![p.phone.clone()],
            "PL" => vec![p.ward.to_string(), p.room.clone(), p.bed.clone()],
            "CX" => {
                let (id, kind) = if name.contains("Account") {
                    (p.account.clone(), "AN")
                } else if name.contains("Visit") {
                    (p.visit_number.clone(), "VN")
                } else {
                    (p.mrn.clone(), "MR")
                };
                let fac = p.facility_code.to_string();
                vec![id, String::new(), String::new(), fac, kind.to_string()]
            }
            "CE" | "CWE" | "CNE" => {
                let (code, text, system) = if name.contains("Diagnosis") {
                    let (c, t) = *self.rng.pick(data::DIAGNOSES);
                    (c.to_string(), t.to_string(), "I10")
                } else if name.contains("Procedure") {
                    let (c, t) = *self.rng.pick(data::PROCEDURES);
                    (c.to_string(), t.to_string(), "C4")
                } else if name.contains("Allerg") {
                    let (c, t, _) = *self.rng.pick(data::ALLERGENS);
                    (c.to_string(), t.to_string(), "")
                } else if name.contains("Insurance Plan") || name.contains("Plan ID") {
                    let plan = *self.rng.pick(data::PLAN_NAMES);
                    (
                        format!("PL{:03}", self.rng.range(1000)),
                        plan.to_string(),
                        "",
                    )
                } else if let Some((key, desc)) = self.table_example(fdef) {
                    // A bound, populated table: real code + its description.
                    (key, desc, "")
                } else {
                    // Nothing meaningful to say: a single neutral identifier
                    // beats an incoherent code^text^system triple.
                    (
                        (*self.rng.pick(data::GENERIC)).to_string(),
                        String::new(),
                        "",
                    )
                };
                return Some(self.ce_parts(dt_id, &code, &text, system));
            }
            "EI" => vec![format!("ORD{:06}", self.rng.range(1_000_000))],
            "HD" => vec![p.facility_code.to_string()],
            "XON" => {
                let org = if name.contains("Insurance") {
                    *self.rng.pick(data::INSURERS)
                } else {
                    *self.rng.pick(data::ORGS)
                };
                vec![encode(org)]
            }
            _ => return None,
        })
    }

    /// Truncate to the type's real component count, drop trailing empties,
    /// and join with the depth-appropriate separator.
    fn join_parts(&mut self, mut parts: Vec<String>, dt_id: &str, depth: u8) -> String {
        if let Some(dt) = self.defs.data_types.get(dt_id) {
            if !dt.components.is_empty() {
                parts.truncate(dt.components.len());
            } else {
                parts.truncate(1);
            }
        } else {
            parts.truncate(1);
        }
        while parts.last().is_some_and(|c| c.is_empty()) {
            parts.pop();
        }
        let sep = if depth == 0 { '^' } else { '&' };
        parts.join(&sep.to_string())
    }

    /// identifier^text^coding-system with the system validated against the
    /// component's bound table (0396) when one exists.
    fn ce_parts(&mut self, dt_id: &str, code: &str, text: &str, system: &str) -> Vec<String> {
        let system = if system.is_empty() {
            String::new()
        } else {
            match self
                .defs
                .data_types
                .get(dt_id)
                .and_then(|dt| dt.components.get(2))
            {
                Some(comp3) => self.coded(system, comp3),
                None => system.to_string(),
            }
        };
        vec![encode(code), encode(text), system]
    }

    fn ce(&mut self, dt_id: &str, code: &str, text: &str, system: &str) -> String {
        let parts = self.ce_parts(dt_id, code, text, system);
        self.join_parts(parts, dt_id, 0)
    }

    /// Prefer `want` when the field has no bound table or the table contains
    /// it; otherwise a random table value keeps the message valid.
    fn coded(&mut self, want: &str, def: &FieldDef) -> String {
        if let Some(table_id) = &def.table {
            if let Some(table) = self.defs.tables.get(table_id) {
                if !table.values.is_empty() && !table.values.contains_key(want) {
                    let keys: Vec<&String> = table.values.keys().collect();
                    return encode(keys[self.rng.range(keys.len() as u64) as usize]);
                }
            }
        }
        encode(&clamp(want, def.length))
    }

    /// A (key, description) sampled from the field's bound table, if any.
    fn table_example(&mut self, def: &FieldDef) -> Option<(String, String)> {
        let table = self.defs.tables.get(def.table.as_ref()?)?;
        if table.values.is_empty() {
            return None;
        }
        let keys: Vec<&String> = table.values.keys().collect();
        let key = keys[self.rng.range(keys.len() as u64) as usize];
        Some((encode(key), encode(&table.values[key])))
    }

    fn components(&mut self, dt: &DataTypeDef, depth: u8, set_id: Option<u64>) -> Vec<String> {
        let mut out: Vec<String> = Vec::new();
        for (j, cdef) in dt.components.iter().enumerate() {
            let fill = j == 0 || cdef.usage == "R" || self.rng.chance(0.3);
            out.push(if fill {
                self.value(&cdef.data_type, cdef, depth + 1, set_id, j + 1)
            } else {
                String::new()
            });
        }
        while out.last().is_some_and(|c| c.is_empty()) {
            out.pop();
        }
        if out.is_empty() {
            out.push(self.leaf("ST", &dt.components[0], set_id));
        }
        out
    }

    fn leaf(&mut self, dt_id: &str, def: &FieldDef, set_id: Option<u64>) -> String {
        // Coded values come from the real table when one is bound and populated;
        // a few well-known fields prefer a specific, realistic member of it.
        if let Some(table_id) = &def.table {
            if self
                .defs
                .tables
                .get(table_id)
                .is_some_and(|t| !t.values.is_empty())
            {
                let name = def.name.as_str();
                let want = if name.contains("Administrative Sex") || name == "Sex" {
                    Some(self.p.sex)
                } else if name.contains("Patient Class") {
                    Some(self.p.patient_class)
                } else {
                    None
                };
                return match want {
                    Some(w) => self.coded(w, def),
                    None => self.table_example(def).map(|(k, _)| k).unwrap_or_default(),
                };
            }
        }
        if def.name.starts_with("Set ID") {
            return set_id.unwrap_or(1).to_string();
        }
        let name = def.name.as_str();
        match dt_id {
            "NM" => {
                if self.rng.chance(0.3) {
                    format!("{}.{}", self.rng.range(400), self.rng.range(10))
                } else {
                    format!("{}", 1 + self.rng.range(400))
                }
            }
            "SI" => format!("{}", set_id.unwrap_or(1 + self.rng.range(9))),
            "DT" => self.coherent_date(name),
            "TM" => format!(
                "{:02}{:02}{:02}",
                6 + self.rng.range(14),
                self.rng.range(60),
                self.rng.range(60)
            ),
            "DTM" | "TS" => self.coherent_dtm(name),
            "TX" | "FT" => encode(&clamp(self.rng.pick(data::NOTES), def.length)),
            "FN" => encode(&clamp(&self.p.patient.family.clone(), def.length)),
            "TN" => self.p.phone.clone(),
            _ => {
                // ST, ID/IS without a usable table, and anything exotic:
                // steer by field name toward the persona or a sensible pool.
                let value: String = if name.contains("Phone") || name.contains("Telecom") {
                    self.p.phone.clone()
                } else if name.contains("Family Name") || name.contains("Surname") {
                    self.p.patient.family.clone()
                } else if name.contains("Given Name") {
                    self.p.patient.given.clone()
                } else if name.contains("Street") {
                    self.p.street.clone()
                } else if name.contains("City") {
                    self.p.city.to_string()
                } else if name.contains("State") || name.contains("Province") {
                    self.p.state.to_string()
                } else if name.contains("Zip") || name.contains("Postal") {
                    self.p.zip.to_string()
                } else if name.contains("Country") {
                    "USA".to_string()
                } else if name.contains("SSN") || name.contains("Social Security") {
                    format!("555{:06}", self.rng.range(1_000_000))
                } else if name.contains("Insurance Company Name") || name.contains("Insurer") {
                    (*self.rng.pick(data::INSURERS)).to_string()
                } else if name.contains("Organization")
                    || name.contains("Employer")
                    || name.contains("Company")
                {
                    (*self.rng.pick(data::ORGS)).to_string()
                } else if name.contains("Facility Name") {
                    self.p.facility_name.to_string()
                } else if name.contains("Comment")
                    || name.contains("Text")
                    || name.contains("Description")
                    || name.contains("Note")
                {
                    (*self.rng.pick(data::NOTES)).to_string()
                } else if name.contains(" ID") || name.contains("Number") {
                    format!("{}", 10_000 + self.rng.range(90_000))
                } else {
                    (*self.rng.pick(data::GENERIC)).to_string()
                };
                encode(&clamp(&value, def.length))
            }
        }
    }

    /// A date that agrees with the persona: birthdays are the DOB, admits and
    /// discharges come from the visit, anything else lands shortly before the
    /// message time.
    fn coherent_date(&mut self, field_name: &str) -> String {
        if field_name.contains("Birth") {
            return self.p.dob.ymd();
        }
        if field_name.contains("Admit") || field_name.contains("Admission") {
            return self.p.admit.ymd();
        }
        if field_name.contains("Discharge") {
            return self.p.discharge.ymd();
        }
        let days = self.rng.range(30) as i64;
        self.p.now.minus_days(days).ymd()
    }

    fn coherent_dtm(&mut self, field_name: &str) -> String {
        let date = if field_name.contains("Birth") {
            // Birth timestamps as date-only - the common real-world shape.
            return self.p.dob.ymd();
        } else if field_name.contains("Admit") || field_name.contains("Admission") {
            self.p.admit.ymd()
        } else if field_name.contains("Discharge") {
            self.p.discharge.ymd()
        } else if field_name.contains("Message") || field_name.contains("Recorded") {
            return self.p.now_dtm();
        } else {
            let days = self.rng.range(10) as i64;
            self.p.now.minus_days(days).ymd()
        };
        if self.rng.chance(0.8) {
            format!(
                "{date}{:02}{:02}{:02}",
                6 + self.rng.range(14),
                self.rng.range(60),
                self.rng.range(60)
            )
        } else {
            date
        }
    }

    /// Break the message on purpose; returns a description of what was done.
    fn inject_defect(
        &mut self,
        lines: &mut Vec<(String, String, bool)>,
        top_required: &[String],
    ) -> Option<String> {
        for _ in 0..8 {
            match self.rng.range(6) {
                // Drop a top-level required segment that occurs exactly once.
                0 => {
                    let victims: Vec<usize> = lines
                        .iter()
                        .enumerate()
                        .filter(|(_, (_, id, _))| {
                            top_required.contains(id)
                                && lines.iter().filter(|(_, lid, _)| lid == id).count() == 1
                        })
                        .map(|(i, _)| i)
                        .collect();
                    if !victims.is_empty() {
                        let i = *self.rng.pick(&victims);
                        let id = lines[i].1.clone();
                        lines.remove(i);
                        return Some(format!("dropped required segment {id}"));
                    }
                }
                // Blank a required field.
                1 => {
                    if let Some(d) =
                        self.mutate_field(lines, |_| String::new(), "blanked required field", true)
                    {
                        return Some(d);
                    }
                }
                // Corrupt a numeric/date field.
                2 => {
                    if let Some(d) = self.corrupt_typed(lines) {
                        return Some(d);
                    }
                }
                // Illegal repetition on a non-repeating field.
                3 => {
                    if let Some(d) = self.mutate_field(
                        lines,
                        |v| format!("{v}~{v}"),
                        "added repetition on non-repeating field",
                        false,
                    ) {
                        return Some(d);
                    }
                }
                // Value that is in no HL7 table.
                4 => {
                    if let Some(d) = self.bogus_table_value(lines) {
                        return Some(d);
                    }
                }
                // Fields beyond the segment definition. Only a segment the defs
                // actually define has a field count to exceed; appending to a
                // Z-segment (or any undefined segment) is lossless positional
                // data the engine keeps with an info note, not a detectable
                // defect - so restrict the target to defined, non-MSH segments.
                5 => {
                    let candidates: Vec<usize> = lines
                        .iter()
                        .enumerate()
                        .filter(|(_, (_, id, _))| {
                            id != "MSH" && self.defs.segments.contains_key(id.as_str())
                        })
                        .map(|(i, _)| i)
                        .collect();
                    if !candidates.is_empty() {
                        let i = *self.rng.pick(&candidates);
                        let id = lines[i].1.clone();
                        let def_len = self.defs.segments[id.as_str()].fields.len();
                        let line = &mut lines[i].0;
                        let current = line.split('|').count() - 1;
                        let pad = def_len.saturating_sub(current) + 2;
                        line.push_str(&"|".repeat(pad));
                        line.push_str("EXTRA");
                        return Some(format!("appended field beyond {id} definition"));
                    }
                }
                _ => unreachable!(),
            }
        }
        None
    }

    /// Apply `f` to a randomly chosen populated field (optionally only
    /// required ones) of a random non-MSH line.
    fn mutate_field(
        &mut self,
        lines: &mut [(String, String, bool)],
        f: impl Fn(&str) -> String,
        what: &str,
        required_only: bool,
    ) -> Option<String> {
        for _ in 0..12 {
            let idx = self.rng.range(lines.len() as u64) as usize;
            let (line, id, _) = &lines[idx];
            if id == "MSH" {
                continue;
            }
            let def = self.defs.segments.get(id.as_str())?;
            let mut parts: Vec<String> = line.split('|').map(String::from).collect();
            let candidates: Vec<usize> = (1..parts.len())
                .filter(|&p| {
                    let fdef = def.fields.get(p - 1);
                    let populated = !parts[p].is_empty();
                    let req = fdef.is_some_and(|fd| fd.usage == "R");
                    let no_rpt = fdef.is_some_and(|fd| fd.rpt == "1");
                    populated && if required_only { req } else { no_rpt }
                })
                .collect();
            if candidates.is_empty() {
                continue;
            }
            let p = *self.rng.pick(&candidates);
            parts[p] = f(&parts[p]);
            let seg = id.clone();
            lines[idx].0 = parts.join("|");
            return Some(format!("{what} {seg}-{p}"));
        }
        None
    }

    fn corrupt_typed(&mut self, lines: &mut [(String, String, bool)]) -> Option<String> {
        for _ in 0..12 {
            let idx = self.rng.range(lines.len() as u64) as usize;
            let (line, id, _) = &lines[idx];
            if id == "MSH" {
                continue;
            }
            let def = self.defs.segments.get(id.as_str())?;
            let mut parts: Vec<String> = line.split('|').map(String::from).collect();
            let candidates: Vec<usize> = (1..parts.len())
                .filter(|&p| {
                    !parts[p].is_empty()
                        && def.fields.get(p - 1).is_some_and(|fd| {
                            matches!(fd.data_type.as_str(), "NM" | "DT" | "DTM" | "SI")
                        })
                })
                .collect();
            if candidates.is_empty() {
                continue;
            }
            let p = *self.rng.pick(&candidates);
            parts[p] = "banana".into();
            let seg = id.clone();
            lines[idx].0 = parts.join("|");
            return Some(format!("corrupted numeric/date {seg}-{p}"));
        }
        None
    }

    fn bogus_table_value(&mut self, lines: &mut [(String, String, bool)]) -> Option<String> {
        for _ in 0..12 {
            let idx = self.rng.range(lines.len() as u64) as usize;
            let (line, id, _) = &lines[idx];
            if id == "MSH" {
                continue;
            }
            let def = self.defs.segments.get(id.as_str())?;
            let mut parts: Vec<String> = line.split('|').map(String::from).collect();
            let candidates: Vec<usize> = (1..parts.len())
                .filter(|&p| {
                    def.fields.get(p - 1).is_some_and(|fd| {
                        fd.table.as_ref().is_some_and(|t| {
                            self.defs
                                .tables
                                .get(t)
                                .is_some_and(|tab| tab.table_type == "HL7" && !tab.values.is_empty())
                        }) && !parts[p].is_empty()
                            // Composite values would bury the bogus code one
                            // level down; keep it a plain field for a clean assert.
                            && !parts[p].contains('^')
                    })
                })
                .collect();
            if candidates.is_empty() {
                continue;
            }
            let p = *self.rng.pick(&candidates);
            parts[p] = "XXQQ".into();
            let seg = id.clone();
            lines[idx].0 = parts.join("|");
            return Some(format!("bogus table value in {seg}-{p}"));
        }
        None
    }
}

/// Respect the spec length of the target field when choosing sample text.
fn clamp(s: &str, len: i64) -> String {
    if len > 0 && s.chars().count() as i64 > len {
        s.chars().take(len as usize).collect()
    } else {
        s.to_string()
    }
}

/// Escape-encode a leaf value with the standard delimiters.
pub fn encode(value: &str) -> String {
    let mut out = String::with_capacity(value.len());
    for ch in value.chars() {
        match ch {
            '\\' => out.push_str("\\E\\"),
            '|' => out.push_str("\\F\\"),
            '^' => out.push_str("\\S\\"),
            '&' => out.push_str("\\T\\"),
            '~' => out.push_str("\\R\\"),
            '\r' => out.push_str("\\X0D\\"),
            '\n' => out.push_str("\\X0A\\"),
            c => out.push(c),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn encode_round_trips_via_engine_decoder() {
        let delims = hl7_engine::syntax::Delimiters::default();
        for raw in ["A|B", "X^Y&Z", "P~Q", "back\\slash", "plain"] {
            let enc = encode(raw);
            assert_eq!(hl7_engine::escape::decode(&enc, &delims), raw);
        }
    }

    #[test]
    fn deterministic_for_a_seed() {
        let bytes = std::fs::read(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../defs/hl7-2.5.1.json"
        ))
        .unwrap();
        let defs = Definitions::from_json(&bytes).unwrap();
        let gen_once = |seed| {
            let mut g = Generator::new(&defs, seed, Config::default());
            g.generate("ORU_R01").unwrap().text
        };
        assert_eq!(gen_once(7), gen_once(7));
        assert_ne!(gen_once(7), gen_once(8));
    }
}
